version: '3.9'
services:
  config-client:
    image: config-client:1.0
    container_name: config-client
    environment:
      - SPRING_PROFILES_ACTIVE:development
      - spring.config.import=optional:configserver:http://config-server:8888\
      - WAIT_HOSTS=config-server:8888
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    ports:
      - '9090:9090'
    depends_on:
       - config-server
    links:
      - config-server
    restart: always
    command: sh -c "/wait && /sayhello"
    networks:
      - config-center

  config-server:
    image: config-server:1.0
    container_name: config-server
    environment:
      - SPRING_CLOUD_CONFIG_SERVER_GIT_URI=https://github.com/satishjbhatkar/config-git-repo
    ports:
      - '8888:8888'
    networks:
      - config-center
    restart: always
networks:
  config-center:
volumes:
  configvolume:

