version: '3'
services:
  api-mongodb:
    image: mongo:latest
    container_name: "api-mongodb"
    volumes:
    - mongodbdata:/data/db
    ports:
      - 27017:27017
  config-client:
    image: client-config:1.0
    container_name: client-config
    ports:
      - '9090:9090'
    depends_on:
      - config-server
      - api-mongodb
  config-client1:
    image: client-config1:1.0
    container_name: client-config1
    ports:
      - '9091:9091'
    depends_on:
      - config-server
      - api-mongodb    
  config-server:
    image: config-server:1.0
    container_name: config-server
    ports:
      - '8888:8888'
volumes:
  mongodbdata: