version: '2'
services:
  config-client:
    image: config-client:1.0
    container_name: config-client
    environment:
      - SPRING_PROFILES_ACTIVE:development
      - spring.config.import=optional:configserver:http://config-server:8888
    ports:
      - '9090:9090'
    depends_on:
      - config-server
    networks:
      - config-center
networks:
   config-center:


